# Generated by Django 4.1.5 on 2023-01-18 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doubles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=100, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("NA", "Prefer not to say"),
                        ],
                        default="NA",
                        max_length=2,
                    ),
                ),
                (
                    "student_number",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(99999999)]
                    ),
                ),
                ("email_address", models.EmailField(max_length=100)),
                ("phone_number", models.CharField(max_length=12)),
                (
                    "skill_level",
                    models.CharField(
                        choices=[("A", "Level A"), ("B", "Level B"), ("C", "Level C")],
                        default="C",
                        max_length=1,
                    ),
                ),
                ("partner_first_name", models.CharField(max_length=100)),
                ("partner_last_name", models.CharField(max_length=100)),
                (
                    "partner_gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("NA", "Prefer not to say"),
                        ],
                        default="NA",
                        max_length=2,
                    ),
                ),
                (
                    "partner_student_number",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(99999999)]
                    ),
                ),
                ("partner_email_address", models.EmailField(max_length=100)),
                ("partner_phone_number", models.CharField(max_length=12)),
                (
                    "partner_skill_level",
                    models.CharField(
                        choices=[("A", "Level A"), ("B", "Level B"), ("C", "Level C")],
                        default="C",
                        max_length=1,
                    ),
                ),
                ("paid_status", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="DoublesWithNoPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=100, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("NA", "Prefer not to say"),
                        ],
                        default="NA",
                        max_length=2,
                    ),
                ),
                (
                    "student_number",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(99999999)]
                    ),
                ),
                ("email_address", models.EmailField(max_length=100)),
                ("phone_number", models.CharField(max_length=12)),
                (
                    "skill_level",
                    models.CharField(
                        choices=[("A", "Level A"), ("B", "Level B"), ("C", "Level C")],
                        default="C",
                        max_length=1,
                    ),
                ),
                ("paid_status", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="MixedDoubles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=100, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("NA", "Prefer not to say"),
                        ],
                        default="NA",
                        max_length=2,
                    ),
                ),
                (
                    "student_number",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(99999999)]
                    ),
                ),
                ("email_address", models.EmailField(max_length=100)),
                ("phone_number", models.CharField(max_length=12)),
                (
                    "skill_level",
                    models.CharField(
                        choices=[("A", "Level A"), ("B", "Level B"), ("C", "Level C")],
                        default="C",
                        max_length=1,
                    ),
                ),
                ("partner_first_name", models.CharField(max_length=100)),
                ("partner_last_name", models.CharField(max_length=100)),
                (
                    "partner_gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("NA", "Prefer not to say"),
                        ],
                        default="NA",
                        max_length=2,
                    ),
                ),
                (
                    "partner_student_number",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(99999999)]
                    ),
                ),
                ("partner_email_address", models.EmailField(max_length=100)),
                ("partner_phone_number", models.CharField(max_length=12)),
                (
                    "partner_skill_level",
                    models.CharField(
                        choices=[("A", "Level A"), ("B", "Level B"), ("C", "Level C")],
                        default="C",
                        max_length=1,
                    ),
                ),
                ("paid_status", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Singles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=100, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("NA", "Prefer not to say"),
                        ],
                        default="NA",
                        max_length=20,
                    ),
                ),
                (
                    "student_number",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(99999999)]
                    ),
                ),
                ("email_address", models.EmailField(max_length=100)),
                ("phone_number", models.CharField(max_length=12)),
                (
                    "skill_level",
                    models.CharField(
                        choices=[("A", "Level A"), ("B", "Level B"), ("C", "Level C")],
                        default="C",
                        max_length=1,
                    ),
                ),
                ("paid_status", models.BooleanField(default=False)),
            ],
        ),
    ]
